git:
  depth: 1

branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint
    - stage: "Build"
      os: osx
      env:
        - Platform="iOS"
        - Type="VanillaJS"
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      before_script: pod repo update
      script:
        - cd src && npm run build
        - cd ../demo && npm i && tns build ios --env.uglify
    - os: osx
      env:
        - Platform="iOS"
        - Type="VueJS"
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      before_script: pod repo update
      script:
        - cd src && npm run build
        - cd ../demo-vue && npm i && tns build ios --env.uglify
    - os: osx
      env:
        - Platform="iOS"
        - Type="Angular"
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      before_script: pod repo update
      script:
        - cd src && npm run build
        - cd ../demo-angular && npm i && tns build ios --env.uglify --env.aot
    - language: android
      os: linux
      dist: trusty
      env:
        - Platform="Android"
        - Type="VanillaJS"
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd src && npm run build
        - cd ../demo && npm i && tns build android --env.uglify --env.snapshot
    - language: android
      os: linux
      dist: trusty
      env:
        - Platform="Android"
        - Type="VueJS"
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd src && npm run build
        - cd ../demo-vue && npm i && tns build android --env.uglify --env.snapshot
    - language: android
      os: linux
      dist: trusty
      env:
        - Platform="Android"
        - Type="Angular"
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - cd src && npm run build
        - cd ../demo-angular && npm i && tns build android --env.uglify --env.snapshot --env.aot
       
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six
        
install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable

